import type { MemberContribution } from './types';
import { subDays, subMonths } from 'date-fns';

export const mockMemberContributions: MemberContribution[] = [
  {
    id: 'c1',
    memberAddress: 'GABC...1234',
    groupId: 'group-1',
    groupName: 'Frontend Team',
    groupColor: '#3b82f6',
    title: 'Refactored auth hook',
    description: 'Simplified useAuth logic and reduced re-renders by 40%',
    timestamp: subMonths(new Date(), 6),
    type: 'contribution',
    amount: 500,
    status: 'completed',
    transactionHash: '0xabc123...',
  },
  {
    id: 'c2',
    memberAddress: 'GABC...1234',
    groupId: 'group-2',
    groupName: 'Backend Team',
    groupColor: '#10b981',
    title: 'Added user API endpoint',
    description: 'Implemented GET /users with pagination and filtering',
    timestamp: subMonths(new Date(), 5),
    type: 'contribution',
    amount: 750,
    status: 'completed',
    transactionHash: '0xdef456...',
  },
  {
    id: 'c3',
    memberAddress: 'GABC...1234',
    groupId: 'group-3',
    groupName: 'Design Team',
    groupColor: '#f59e0b',
    title: 'Updated color palette',
    description: 'Migrated to new brand colors in Figma and design tokens',
    timestamp: subMonths(new Date(), 5),
    type: 'contribution',
    amount: 300,
    status: 'completed',
  },
  {
    id: 'c4',
    memberAddress: 'GABC...1234',
    groupId: 'group-1',
    groupName: 'Frontend Team',
    groupColor: '#3b82f6',
    title: 'Fixed navigation bug',
    description: 'Resolved active state issue in sidebar navigation',
    timestamp: subMonths(new Date(), 4),
    type: 'contribution',
    amount: 250,
    status: 'completed',
  },
  {
    id: 'c5',
    memberAddress: 'GABC...1234',
    groupId: 'group-4',
    groupName: 'DevOps Team',
    groupColor: '#8b5cf6',
    title: 'Setup CI pipeline',
    description: 'Configured GitHub Actions for auto-deploy to staging',
    timestamp: subMonths(new Date(), 4),
    type: 'member_join',
    status: 'completed',
  },
  {
    id: 'c6',
    memberAddress: 'GABC...1234',
    groupId: 'group-2',
    groupName: 'Backend Team',
    groupColor: '#10b981',
    title: 'Optimized database queries',
    description: 'Added indexes for slow queries on orders table',
    timestamp: subMonths(new Date(), 3),
    type: 'contribution',
    amount: 600,
    status: 'completed',
    transactionHash: '0xghi789...',
  },
  {
    id: 'c7',
    memberAddress: 'GABC...1234',
    groupId: 'group-1',
    groupName: 'Frontend Team',
    groupColor: '#3b82f6',
    title: 'Implemented dashboard',
    description: 'Built main analytics dashboard view with charts',
    timestamp: subMonths(new Date(), 3),
    type: 'contribution',
    amount: 800,
    status: 'completed',
  },
  {
    id: 'c8',
    memberAddress: 'GABC...1234',
    groupId: 'group-3',
    groupName: 'Design Team',
    groupColor: '#f59e0b',
    title: 'Design system tokens',
    description: 'Created shared token library for spacing and typography',
    timestamp: subMonths(new Date(), 2),
    type: 'contribution',
    amount: 400,
    status: 'completed',
  },
  {
    id: 'c9',
    memberAddress: 'GABC...1234',
    groupId: 'group-4',
    groupName: 'DevOps Team',
    groupColor: '#8b5cf6',
    title: 'Kubernetes manifests',
    description: 'Added Helm charts for staging environment deployment',
    timestamp: subMonths(new Date(), 2),
    type: 'contribution',
    amount: 550,
    status: 'completed',
  },
  {
    id: 'c10',
    memberAddress: 'GABC...1234',
    groupId: 'group-1',
    groupName: 'Frontend Team',
    groupColor: '#3b82f6',
    title: 'TypeScript migration',
    description: 'Converted remaining JS files to TypeScript',
    timestamp: subMonths(new Date(), 1),
    type: 'contribution',
    amount: 700,
    status: 'completed',
  },
  {
    id: 'c11',
    memberAddress: 'GABC...1234',
    groupId: 'group-2',
    groupName: 'Backend Team',
    groupColor: '#10b981',
    title: 'Added caching layer',
    description: 'Integrated Redis for session storage and caching',
    timestamp: subDays(new Date(), 20),
    type: 'contribution',
    amount: 650,
    status: 'completed',
  },
  {
    id: 'c12',
    memberAddress: 'GABC...1234',
    groupId: 'group-3',
    groupName: 'Design Team',
    groupColor: '#f59e0b',
    title: 'Mobile responsive audit',
    description: 'Reviewed and fixed mobile layouts across all screens',
    timestamp: subDays(new Date(), 15),
    type: 'contribution',
    amount: 350,
    status: 'completed',
  },
  {
    id: 'c13',
    memberAddress: 'GABC...1234',
    groupId: 'group-4',
    groupName: 'DevOps Team',
    groupColor: '#8b5cf6',
    title: 'Monitoring alerts',
    description: 'Setup PagerDuty integration for critical alerts',
    timestamp: subDays(new Date(), 10),
    type: 'contribution',
    amount: 450,
    status: 'pending',
  },
  {
    id: 'c14',
    memberAddress: 'GABC...1234',
    groupId: 'group-1',
    groupName: 'Frontend Team',
    groupColor: '#3b82f6',
    title: 'Dark mode support',
    description: 'Added theme toggle and dark palette support',
    timestamp: subDays(new Date(), 5),
    type: 'contribution',
    amount: 500,
    status: 'completed',
  },
  {
    id: 'c15',
    memberAddress: 'GABC...1234',
    groupId: 'group-2',
    groupName: 'Backend Team',
    groupColor: '#10b981',
    title: 'Database backup automation',
    description: 'Automated daily backups to S3 with retention policy',
    timestamp: subDays(new Date(), 2),
    type: 'cycle_complete',
    status: 'completed',
  },
];

